version: '3.8'
services:
  postgres:
    image: postgres:14.0-alpine
    container_name: service_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - '5432:5432'
    networks:
      - revel_shop

  postgres_test:
    image: postgres:14.0-alpine
    container_name: test_db
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
      DATABASE_HOST: ${TEST_DB_HOST}
    ports:
      - '5433:5432'
    networks:
      - revel_shop

  app:
    container_name: revel_app
    build: .
    ports:
      - '4141:4141'
    environment:
      MAX_BASKET_SIZE: ${MAX_BASKET_SIZE}
      DISCOUNT_THRESHOLD: ${DISCOUNT_THRESHOLD}
      DISCOUNT: ${DISCOUNT}
      FREE_ITEM_THRESHOLD: ${FREE_ITEM_THRESHOLD}

      DB_HOST: ${DB_HOST}
      DB_DRIVER: ${DB_DRIVER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

      # Postgres Test
      TEST_DB_HOST: ${TEST_DB_HOST}
      TEST_DB_DRIVER: ${TEST_DB_DRIVER}
      TEST_DB_USER: ${TEST_DB_USER}
      TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}
      TEST_DB_PORT: ${TEST_DB_PORT}

    restart: on-failure
    depends_on:
      - postgres
      - postgres_test
    networks:
      - revel_shop

networks:
  revel_shop:
    driver: bridge