version: '3.8'
services:
  app:
    container_name: revel_app
    build: .
    ports:
      - '4141:4141'
    environment:
      # Cart Rules
      - MAX_BASKET_SIZE=100
      - DISCOUNT_THRESHOLD=20
      - DISCOUNT=1
      - FREE_ITEM_THRESHOLD=5

      # Postgres connection
      - DB_HOST=postgres
      - DB_DRIVER=postgres
      - DB_USER=revel
      - DB_PASSWORD=revel
      - DB_NAME=revel
      - DB_PORT=5432

      # Postgres Test
      - TEST_DB_HOST=postgres_test
      - TEST_DB_DRIVER=postgres
      - TEST_DB_USER=revel
      - TEST_DB_PASSWORD=revel
      - TEST_DB_NAME=revel_test
      - TEST_DB_PORT=5433
    restart: on-failure
    depends_on:
      - service_db
      - test_db
    networks:
      - revel_shop

  postgres:
    image: postgres:14.0-alpine
    container_name: service_db
    environment:
      - POSTGRES_USER=revel
      - POSTGRES_PASSWORD=revel
      - POSTGRES_DB=revel
    ports:
      - '5432:5432'
    networks:
      - revel_shop

  postgres_test:
    image: postgres:14.0-alpine
    container_name: test_db
    environment:
      - POSTGRES_USER=revel
      - POSTGRES_PASSWORD=revel
      - POSTGRES_DB=revel_test
    ports:
      - '5433:5432'
    networks:
      - revel_shop

networks:
  revel_shop:
    driver: bridge