version: '3'
services:
  app:
    container_name: shopping_app
    build: .
    ports:
      - 4141:4141
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - revel


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=revel
      - POSTGRES_PASSWORD=revel
      - POSTGRES_DB=revel
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - revel

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  revel:
    driver: bridge
