version: '3'
services:
  app:
    container_name: revel_shop
    build: .
    ports:
      - '4141:4141'
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
      - postgres_test
    networks:
      - revel_shop

  postgres:
    image: postgres:latest
    container_name: service_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - revel_shop

  postgres_test:
    image: postgres:latest
    container_name: test_db
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - '5433:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - revel_shop

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  revel_shop: