version: "3.8"

services:
  database:
    container_name: postgres
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=revel
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB = revel
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: