// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Simas Paulikas",
            "email": "simaspaulikas@yahoo.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/carts/{customer_id}": {
            "get": {
                "description": "Returns cart items given customer ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carts"
                ],
                "summary": "Returns cart.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the item to retrieve",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.CartItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Item doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/carts/{customer_id}/items/{item_id}": {
            "post": {
                "description": "Adds item given an ID to a given customer cart.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carts"
                ],
                "summary": "Adds item to cart.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the customer to whose cart the item is added",
                        "name": "customer_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of an item that is being added",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.CartItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Item doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/carts/{customer_id}/orders": {
            "post": {
                "description": "Places an order for a given customers cart.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carts"
                ],
                "summary": "Places an order.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the customer who is making the order",
                        "name": "customer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order has been place",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.CartItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Item doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/carts/{customer_id}/totals": {
            "post": {
                "description": "Returns cart total for a given customer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carts"
                ],
                "summary": "Returns cart total.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the customer for whom to retrieve total",
                        "name": "customer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.CartItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Item doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/items/{item_id}": {
            "get": {
                "description": "get item by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Show an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the item to retrieve",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Item"
                        }
                    },
                    "400": {
                        "description": "Item doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create an item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Create an item",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Item"
                        }
                    },
                    "400": {
                        "description": "Item already exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes item from catalog",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Removes item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the item to delete",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Item"
                        }
                    },
                    "400": {
                        "description": "Item doesn't exist",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CartItem": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "unit_price": {
                    "type": "integer"
                }
            }
        },
        "model.Item": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "stock": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4141",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Revel Shopping API",
	Description:      "Shopping API for Revel.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
