basePath: /api/v1
definitions:
  model.CartItem:
    properties:
      quantity:
        type: integer
      unit_price:
        type: integer
    type: object
  model.Item:
    properties:
      category:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
    type: object
host: localhost:4141
info:
  contact:
    email: simaspaulikas@yahoo.com
    name: Simas Paulikas
  description: Shopping API for Revel.
  title: Revel Shopping API
  version: "1.0"
paths:
  /carts/{customer_id}:
    get:
      description: Returns cart items given customer ID.
      parameters:
      - description: ID of the item to retrieve
        in: path
        name: item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
        "400":
          description: Item doesn't exist
          schema:
            type: string
      summary: Returns cart.
      tags:
      - carts
  /carts/{customer_id}/items/{item_id}:
    post:
      description: Adds item given an ID to a given customer cart.
      parameters:
      - description: ID of the customer to whose cart the item is added
        in: path
        name: customer_id
        required: true
        type: string
      - description: ID of an item that is being added
        in: path
        name: item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
        "400":
          description: Item doesn't exist
          schema:
            type: string
      summary: Adds item to cart.
      tags:
      - carts
  /carts/{customer_id}/orders:
    post:
      description: Places an order for a given customers cart.
      parameters:
      - description: ID of the customer who is making the order
        in: path
        name: customer_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Order has been place
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
        "500":
          description: Item doesn't exist
          schema:
            type: string
      summary: Places an order.
      tags:
      - carts
  /carts/{customer_id}/totals:
    post:
      description: Returns cart total for a given customer.
      parameters:
      - description: ID of the customer for whom to retrieve total
        in: path
        name: customer_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
        "400":
          description: Item doesn't exist
          schema:
            type: string
      summary: Returns cart total.
      tags:
      - carts
  /items/{item_id}:
    delete:
      description: Removes item from catalog
      parameters:
      - description: ID of the item to delete
        in: path
        name: item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
        "400":
          description: Item doesn't exist
          schema:
            type: string
      summary: Removes item
      tags:
      - items
    get:
      description: get item by ID
      parameters:
      - description: ID of the item to retrieve
        in: path
        name: item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
        "400":
          description: Item doesn't exist
          schema:
            type: string
      summary: Show an item
      tags:
      - items
    post:
      consumes:
      - application/json
      description: Create an item
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
        "400":
          description: Item already exist
          schema:
            type: string
      summary: Create an item
      tags:
      - items
swagger: "2.0"
