basePath: /api/v1
definitions:
  model.CartItem:
    properties:
      quantity:
        type: integer
      unit_price:
        type: integer
    type: object
  model.Item:
    properties:
      category:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
    type: object
host: localhost:4141
info:
  contact:
    email: simaspaulikas@yahoo.com
    name: Simas Paulikas
  description: Shopping API for Revel.
  title: Revel Shopping API
  version: "1.0"
paths:
  /carts/{customer_id}:
    get:
      description: Removes item from catalog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
      summary: Removes item
      tags:
      - carts
  /carts/{customer_id}/items/{item_id}:
    post:
      description: Removes item from catalog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
      summary: Removes item
      tags:
      - carts
  /carts/{customer_id}/orders:
    post:
      description: Removes item from catalog
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
      summary: Removes item
      tags:
      - carts
  /carts/{customer_id}/totals:
    post:
      description: Removes item from catalog
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/model.CartItem'
            type: object
      summary: Removes item
      tags:
      - carts
  /items/{item_id}:
    delete:
      description: Removes item from catalog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
      summary: Removes item
      tags:
      - items
    get:
      description: get item by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
      summary: Show an item
      tags:
      - items
    post:
      consumes:
      - application/json
      description: Create an item
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
      summary: Create an item
      tags:
      - items
swagger: "2.0"
